**Problem Statement**

The y = target is to maximize this equation ASAP <br/>
`y = (w1 * x1) + (w2 * x2) + (w3 * x3) + (w4 * x4) + (w5 * x5) + (6w * x6)` <br/>
where <br/> 
`(x1, x2, x3, x4, x5, x6) = (4, -2, 3.5, 5, -11, -4.7)`

---

- What are the best values for the 6 weights w1 to w6?
- We are going to use the genetic algorithm for the best possible values after a number of generations.

---
**Initialize equation inputs :**

In [19]:
import numpy

# Inputs of the Equation
equation_inputs = [4, -2, 3.5, 5, -11, -4.7]

# Number of weights to be optimized
num_weights = 6

---
**Genetic algorithm parameters :**
- Mating pool size
- Population size

In [20]:
solution_per_population = 8
num_parents_mating = 4

---
**Creation of a population :**

In [21]:
# Defining the population size
# The population will have solution per population chromosome where each chromosome has num of weights genes
population_size = (solution_per_population, num_weights) 

# Creating the initial population
new_population = numpy.random.uniform(low=-4.0, high=4.0, size = population_size)
print(new_population)

[[ 3.27041601  0.94077549  0.44131624  1.83041256  1.67470965  3.13927158]
 [ 3.84687022 -1.24528875 -3.81549802  0.12190864  1.27927097 -3.80432504]
 [-0.92353159 -1.77627782 -3.281175    0.93036445 -0.84497689 -2.2792554 ]
 [-0.0622672   2.75506323 -1.03257699 -2.91307512  3.38787124 -1.21428905]
 [-0.41172594  2.92535939 -3.85624053 -1.30798046  3.53946993  0.70259583]
 [-1.36264749  0.53837792 -2.19650854 -2.269148    3.33010662 -0.02369836]
 [ 1.69717225 -3.34407498 -0.80984937 -3.49045293 -2.97387518  1.45993163]
 [ 0.69483804  0.67784739 -3.21527153  2.76231612  3.17101655  2.21183312]]


---
**Defining genetic algorithm functions for the ff :**
- Calculation of population fitness
- Selection of mating pool
- Offspring crossover
- Crossover mutation

In [22]:
def cal_population_fitness(equation_inputs, population):
    # Calculating the fitness value of each solution in the current population.
    # The fitness function caulcuates the sum of products between each input and its corresponding weight.
    fitness = numpy.sum(population * equation_inputs, axis = 1)
    return fitness

def select_mating_pool(population, fitness, num_parents):
    # Selecting the best individuals in the current generation as parents for producing the offspring of the next generation.
    parents = numpy.empty((num_parents, population.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = population[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    # The point at which crossover takes place between two parents. Usually it is at the center.
    crossover_point = numpy.uint8(offspring_size[1] / 2)
    for k in range(offspring_size[0]):
        # Index of the first parent to mate.
        parent1_idx = k % parents.shape[0]
        # Index of the second parent to mate.
        parent2_idx = (k + 1) % parents.shape[0]
        # The new offspring will have its first half of its genes taken from the first parent.
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        # The new offspring will have its second half of its genes taken from the second parent.
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

def mutation(offspring_crossover):
    # Mutation changes a single gene in each offspring randomly.
    for idx in range(offspring_crossover.shape[0]):
        # The random value to be added to the gene.
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

---
**Generation creation and training :**

In [23]:
num_generations = 5

for generation in range(num_generations):
    print("Generation : ", generation)
    
    # Measing the fitness of each chromosome in the population.
    fitness = cal_population_fitness(equation_inputs, new_population)

    # Selecting the best parents in the population for mating.
    parents = select_mating_pool(new_population, fitness, num_parents_mating)

    # Generating next generation using crossover.
    offspring_crossover = crossover(parents, offspring_size = (population_size[0] - parents.shape[0], num_weights))

    # Adding some variations to the offsrping using mutation.
    offspring_mutation = mutation(offspring_crossover)

    # Creating the new population based on the parents and offspring.
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    # The best result in the current iteration.
    print("Best result : ", numpy.max(numpy.sum(new_population * equation_inputs, axis=1)))

Generation :  0
Best result :  33.656634129235904
Generation :  1
Best result :  36.20535637547718
Generation :  2
Best result :  40.84165332153658
Generation :  3
Best result :  41.45567265265902
Generation :  4
Best result :  51.22471185825478


---
**Getting results from generation training :**

In [24]:
# Getting the best solution after iterating finishing all generations.
# At first, the fitness is calculated for each solution in the final generation.
fitness = cal_population_fitness(equation_inputs, new_population)

# Then return the index of that solution corresponding to the best fitness.
best_match_idx = numpy.where(fitness == numpy.max(fitness))

print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])

Best solution :  [[[ 1.69717225 -3.34407498 -0.80984937  0.93036445 -2.29254755
   -2.2792554 ]]]
Best solution fitness :  [51.22471186]
